DROP TABLE IF EXISTS ems_user_session;
DROP TABLE IF EXISTS ems_user_detail;

CREATE TABLE ems_user_detail(
		USER_ID INT NOT NULL AUTO_INCREMENT,
		USER_NAME VARCHAR(20) NOT NULL,
		PASSWORD VARCHAR(20) NOT NULL,
		EMAIL_ID VARCHAR(40) NOT NULL,
        MOBILE_NUMBER VARCHAR(20) NOT NULL,
 		IS_ACTIVE VARCHAR(1),
 		CREATED_BY VARCHAR(100),
 		CREATED_DATE DATETIME,
 		UPDATED_BY VARCHAR(100),
 		UPDATED_DATE DATETIME,
 		
		CONSTRAINT ems_user_detail_PK PRIMARY KEY(USER_ID)
)
AUTO_INCREMENT = 1;

CREATE TABLE ems_user_session(
		SESSION_ID INT NOT NULL AUTO_INCREMENT,
		USER_ID INT NOT NULL,
		LOGIN_TIME DATETIME,
        LOGOUT_TIME DATETIME,
 		IS_ACTIVE VARCHAR(1),
 		CREATED_BY VARCHAR(100),
 		CREATED_DATE DATETIME,
 		CONSTRAINT ems_user_detail_FK FOREIGN KEY (USER_ID) REFERENCES ems_user_detail(USER_ID),
		CONSTRAINT ems_user_session_PK PRIMARY KEY(SESSION_ID)
)
AUTO_INCREMENT = 1000000;
