DROP TABLE IF EXISTS ems_employee_detail;

CREATE TABLE ems_employee_detail(
		EMP_ID INT NOT NULL AUTO_INCREMENT,
		EMP_NAME VARCHAR(100) NOT NULL,
 		SALARY DECIMAL NOT NULL,
		DATE_OF_JOINING DATE,
        DATE_OF_RESIGN DATE,
 		IS_ACTIVE VARCHAR(1),
 		CREATED_BY VARCHAR(100),
 		CREATED_DATE DATETIME,
 		UPDATED_BY VARCHAR(100),
 		UPDATED_DATE DATETIME, 		 
		CONSTRAINT employee_detail_PK PRIMARY KEY(EMP_ID)
)
AUTO_INCREMENT = 1;
